---
title: Voeg een variabele toe in Scratch
hero_image: images / banner.png
description: Hoe een variabele in Scratch toe te voegen
original_url: ""
theme: cc-prototype
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Maak een variabele
