title: Scratch में वेरिएबल शामिल करें
hero_image: images/banner.png
description: Scratch में वेरिएबल कैसे शामिल करें
original_url:
theme: cc-prototype
duration: 1 # 1, 2 or 3
curriculum:
listed: false
ingredient: true
copyedit: true
interests: “"
technologies: “"
steps:
  - title: वेरिएबल बनाएँ
