---
title: Legg til en variabel i Scratch
hero_image: images / banner.png
description: Slik legger du til en variabel i Scratch
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Lag en variabel
