---
title: Thêm biến trong Scratch
hero_image: images / banner.png
description: Cách thêm biến trong Scratch
original_url:
theme: nguyên mẫu cc
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Tạo biến
