---
title: Adicione uma vari치vel em Scratch
hero_image: images / banner.png
description: Como adicionar uma vari치vel em Scratch
original_url:
theme: prot칩tipo cc
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Criar uma vari치vel
