---
title: 在Scratch中添加一个变量
hero_image: 图片/ banner.png
description: 如何在Scratch中添加一个变量
original_url:
theme: CC-原型
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: 创建一个变量
