---
title: Dodaj varijablu u Scratch
hero_image: images/banner.png
description: Kako dodati varijablu u Scratch
original_url: ""
theme: cc-prototype
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Stvori varijablu
