---
title: Dodajte varijablu u Scratch
hero_image: slike / banner.png
description: Kako dodati varijablu u Scratch
original_url: ""
theme: cc-prototip
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Stvorite varijablu
