---
title: Lisää muuttuja tyhjäksi
hero_image: Kuvien / banner.png
description: Muuttujan lisääminen Scratchiin
original_url: ""
theme: CC-prototyyppi
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Luo muuttuja
