---
title: Lis채채 muuttuja Scratchissa
hero_image: images/banner.png
description: Muuttujan lis채채minen Scratchissa
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Luo muuttuja
