---
title: Ychwanegu newidyn yn Scratch
hero_image: delweddau / banner.png
description: Sut i ychwanegu newidyn yn Scratch
original_url:
theme: cc-prototeip
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Creu newidyn
