---
title: Füge eine Variable in Scratch hinzu
hero_image: images/banner.png
description: Wie man eine Variable in Scratch hinzufügt
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - title: Erstelle eine Variable
