---
title: Adăugați o variabilă în Scratch
hero_image: images/banner.png
description: Cum se adaugă o variabilă în Scratch
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Creați o variabilă
