---
title: Menambahkan sebuah variabel pada Scratch
hero_image: images/banner.png
description: Cara menambahkan variabel dalam Scratch
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Membuat sebuah variabel
