---
title: Tambahkan variabel dalam Scratch
hero_image: gambar / banner.png
description: Cara menambahkan variabel dalam Scratch
original_url: ""
theme: cc-prototipe
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Buat sebuah variabel
