---
title: הוסף משתנה ב- Scratch
hero_image: תמונות / banner.png
description: כיצד להוסיף משתנה ב- Scratch
original_url:
theme: אב טיפוס
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: צור משתנה
