---
title: Adjon hozzá egy változót a Scratch-ban
hero_image: images / banner.png
description: Hogyan lehet hozzáadni egy változót a Scratch-ban?
original_url:
theme: cc-prototípus
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Hozzon létre egy változót
