---
title: Dodaj zmienną w Scratch
hero_image: images / banner.png
description: Jak dodać zmienną w Scratch
original_url:
theme: prototyp cc
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Utwórz zmienną
