---
title: Pridajte premennú v aplikácii Scratch
hero_image: images / banner.png
description: Ako pridať premennú v aplikácii Scratch
original_url: ""
theme: cc-prototyp
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Vytvorte premennú
