---
title: Pridanie premennej v jazyku Scratch
hero_image: images / banner.png
description: How to add a variable in Scratch
original_url:
theme: cc-prototyp
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Vytvorte premennú
