---
title: L채gg till en variabel i Scratch
hero_image: images / banner.png
description: S책 h채r l채gger du till en variabel i Scratch
original_url:
theme: cc-prototyp
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Skapa en variabel
