---
title: Tambah pemboleh ubah dalam Gores
hero_image: imej / banner.png
description: Bagaimana untuk menambah pemboleh ubah dalam Gores
original_url:
theme: prototaip cc
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Buat pembolehubah
