---
title: Creare una variabile in Scratch
hero_image: images/banner.png
description: Come creare una variabile in Scratch
original_url: ""
theme: cc-prototype
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Crea una variabile
