---
title: Scratch'te bir değişken ekle
hero_image: images/banner.png
description: Scratch'te bir değişken nasıl eklenir
original_url:
theme: cc-prototype
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Bir değişken oluştur
